version: "3"

vars:
  DOCKER_COMPOSE: "docker compose"
  CONTAINER_DB: "db"
  CONTAINER_APP: "app"
  DB_URL: "postgresql://$DB_USER:$DB_PASSWORD@localhost:5432/$DB_DATABASE?sslmode=disable"
  CMD: "cmd/tiny/main.go"

dotenv: [".env", "{{.ENV}}/.env", "{{.HOME}}/.env"]

tasks:
  build:
    cmds:
      - go build -o bin/tiny ./{{.CMD}}

  up:
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  build-docker:
    cmds:
      - docker compose up -d --build

  restart:
    cmds:
      - docker compose restart

  down-volumes:
    cmds:
      - docker compose down --volumes

  migrate_version:
    cmds:
      - migrate -path migrations -database "{{.DB_URL}}" version
    silent: true

  migrate_reset:
    cmds:
      - migrate -path migrations -database "{{.DB_URL}}" force 1
    silent: true

  migrate_up:
    cmds:
      - migrate -path migrations -database "{{.DB_URL}}" -verbose up
    silent: true

  migrate_down:
    cmds:
      - migrate -path migrations -database "{{.DB_URL}}" -verbose down
    silent: true

  db_seed:
    cmds:
      - echo "TODO"

  swagger:
    cmds:
      - swag init -g {{.CMD}}
