app_name: "tiny"
env: "local"
debug: true
alias_length: 6
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
db:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_DATABASE}
