app_name: "tiny"
env: "prod"
debug: false
alias_length: 6
http_server:
  address: "localhost:8080" 
  timeout: 4s
  idle_timeout: 4s
db:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  name: ${DB_DATABASE}
