definitions:
  httpserver.Request:
    properties:
      short_url:
        type: string
      url:
        type: string
    required:
    - url
    type: object
  httpserver.Response:
    properties:
      message: {}
    type: object
  httpserver.UrlList:
    properties:
      page:
        type: integer
      size:
        type: integer
      total_count:
        type: integer
      total_pages:
        type: integer
      urls:
        items:
          $ref: '#/definitions/models.URL'
        type: array
    type: object
  models.URL:
    properties:
      created_at:
        type: string
      id:
        type: integer
      short_url:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /{short_url}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Shortened URL
        in: path
        name: short_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Found
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpserver.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpserver.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpserver.Response'
      summary: Redirect URL
      tags:
      - URL
  /url:
    post:
      consumes:
      - application/json
      parameters:
      - description: URL
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/httpserver.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpserver.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpserver.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpserver.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpserver.Response'
      summary: Save URL
      tags:
      - URL
  /url/{short_url}:
    delete:
      consumes:
      - application/json
      description: delete url by short url
      parameters:
      - description: Short of the URL
        in: path
        name: short_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.URL'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpserver.Response'
      summary: Delete URL
      tags:
      - URL
    get:
      consumes:
      - application/json
      description: get url string by short url
      parameters:
      - description: Short of the URL
        in: path
        name: short_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.URL'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpserver.Response'
      summary: Get URL
      tags:
      - URL
  /url/all:
    get:
      consumes:
      - application/json
      description: get urls
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpserver.UrlList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpserver.Response'
      summary: Get All URLs
      tags:
      - URL
swagger: "2.0"
