name: Deploy App

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/go/Dockerfile 
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/tiny-url:latest

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      DEPLOY_DIR: /app
      CONFIG_PATH: /app/config/prod.yml
    steps:
      # - name: Create app directory if not exists
      #   run: mkdir -p /home/ec2-user/app

      - name: Create .env from Secret
        run: echo "${{ secrets.ENV_FILE }}" > /home/ec2-user/app/.env
        working-directory: ${{ env.DEPLOY_DIR }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          path: /app

      - name: Pull latest image
        run: docker pull ${{ vars.DOCKER_USERNAME }}/tiny-url:latest

      - name: Stop running containers
        working-directory: /app
        run: docker compose down

      - name: Start services
        working-directory: /app
        run: docker compose up -d --force-recreate --remove-orphans

      - name: Clean up unused images
        run: docker image prune -f
