name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi

      - name: Create .env from Secret
        run: echo "${{ secrets.ENV_FILE }}" > .env
        working-directory: ${{ env.DEPLOY_DIR }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

  deploy:
    env:
      DEPLOY_DIR: /home/ec2-user/app
      CONFIG_PATH: /home/ec2-user/app/config/prod.yml
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Stop and Remove Old Containers
        run: docker compose down

      - name: Start Services with Docker Compose
        run: docker compose up -d --force-recreate --remove-orphans

