name: Deploy App

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/go/Dockerfile 
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/tiny-url:latest

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      DEPLOY_DIR: /home/ec2-user/app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Ensure deploy directory exists and sync files
        run: |
          mkdir -p $DEPLOY_DIR
          rsync -a --delete --exclude=".env" $GITHUB_WORKSPACE/ $DEPLOY_DIR/

      - name: Create .env if not exists
        run: |
          if [ ! -f "$DEPLOY_DIR/.env" ]; then
            echo "${{ secrets.ENV_FILE }}" > $DEPLOY_DIR/.env
          fi

      - name: Pull latest image
        run: docker pull ${{ vars.DOCKER_USERNAME }}/tiny-url:latest

      - name: Stop running containers
        working-directory: ${{ env.DEPLOY_DIR }}
        run: docker compose down

      - name: Start services
        working-directory: ${{ env.DEPLOY_DIR }}
        run: docker compose up -d --force-recreate --remove-orphans

      - name: Clean up unused images
        run: docker image prune -f

